#! /usr/bin/env php

<?php
use Acme\ShowCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Movies App', '1.0');


/*//connect to the database:
try
{
    $pdo = new PDO('sqlite:db.sqlite');
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
}

catch (Exception $exception){
    echo 'Could not connect to the database';
    exit(1);
}

$dbAdapter = new Acme\DatabaseAdapter($pdo);

$app->add(new Acme\ShowCommand($dbAdapter)); //pass the adapter to the showcommand*/
$app->add(new ShowCommand);

$app->run();