#! /usr/bin/env php

<?php
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;


require 'vendor/autoload.php';

$app = new Application('Movies App', '1.0');


/*//connect to the database:
try
{
    $pdo = new PDO('sqlite:db.sqlite');
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
}

catch (Exception $exception){
    echo 'Could not connect to the database';
    exit(1);
}

$dbAdapter = new Acme\DatabaseAdapter($pdo);

$app->add(new Acme\ShowCommand($dbAdapter)); //pass the adapter to the showcommand*/

$app->register('show')
    ->addArgument('movieTitle')
    ->setCode(function(InputInterface $input, OutputInterface $output){
        $output->writeln('Hello');
    });

$app->run();